updated GHA dependencies, added Junit report publisher step

diff --git a/.github/workflows/manual-run-standalone-browser.yml b/.github/workflows/manual-run-standalone-browser.yml
--- a/.github/workflows/manual-run-standalone-browser.yml
+++ b/.github/workflows/manual-run-standalone-browser.yml
@@ -24,9 +24,26 @@ permissions:
   id-token: write
 
 jobs:
-  build:
+  prepare:
     runs-on: ubuntu-latest
+    outputs:
+      BROWSER: ${{ steps.prepare.outputs.BROWSER }}
+      ALLURE_LINK: ${{ steps.prepare.outputs.ALLURE_LINK }}
 
+    steps:
+      - name: Prepare
+        id: prepare
+        run: |
+          echo "BROWSER=${{ inputs.BROWSER }}" >> $GITHUB_OUTPUT
+          echo "ALLURE_LINK=https://mrc81.github.io/Cucumber_Selenide" >> $GITHUB_OUTPUT
+
+      - name: Adding markdown
+        run: |
+          echo "- BROWSER: ${{ steps.prepare.outputs.BROWSER }}" >> $GITHUB_STEP_SUMMARY
+
+  run_auto_test:
+    runs-on: ubuntu-latest
+    needs: [prepare]
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4.1.1
@@ -73,6 +90,12 @@ jobs:
           ./gradlew clean test -Dselenide.headless=true -Dselenide.browser="${{ inputs.BROWSER }}"
         continue-on-error: true
 
+      - name: Publish JUnit Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
+
       - name: Get Allure history
         uses: actions/checkout@v4.1.1
         if: always()
@@ -93,7 +116,7 @@ jobs:
 
       - name: Deploy report to Github Pages
         if: always()
-        uses: peaceiris/actions-gh-pages@v3.9.3
+        uses: peaceiris/actions-gh-pages@v4.0.0
 
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
