updated both manual pipelines

diff --git a/.github/workflows/manual-run-selenoid.yml b/.github/workflows/manual-run-selenoid.yml
--- a/.github/workflows/manual-run-selenoid.yml
+++ b/.github/workflows/manual-run-selenoid.yml
@@ -16,17 +16,46 @@ on:
           - chrome
           - firefox
           - edge
+          - safari
         default: chrome
+      VERSION:
+        type: choice
+        required: true
+        description: Select the browser version
+        options:
+          - latest
+          - "122.0"
+          - "121.0"
+          - "120.0"
+        default: latest
 
 permissions:
   contents: write
   pages: write
   id-token: write
+  checks: write
 
 jobs:
-  build:
+  prepare:
     runs-on: ubuntu-latest
+    outputs:
+      BROWSER: ${{ steps.prepare.outputs.BROWSER }}
+      ALLURE_LINK: ${{ steps.prepare.outputs.ALLURE_LINK }}
 
+    steps:
+      - name: Prepare
+        id: prepare
+        run: |
+          echo "BROWSER=${{ inputs.BROWSER }}" >> $GITHUB_OUTPUT
+          echo "ALLURE_LINK=https://mrc81.github.io/Cucumber_Selenide" >> $GITHUB_OUTPUT
+
+      - name: Adding markdown
+        run: |
+          echo "- BROWSER: ${{ steps.prepare.outputs.BROWSER }}" >> $GITHUB_STEP_SUMMARY
+
+  run_tests:
+    runs-on: ubuntu-latest
+    needs: [ prepare ]
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4.1.1
@@ -42,6 +71,7 @@ jobs:
         with:
           selenoid-start-arguments: |
             --browsers-json "./browsers.json"
+            --version "${{ inputs.VERSION }}"
         id: start-selenoid
         continue-on-error: false
 
@@ -60,6 +90,17 @@ jobs:
         run: |
           ./gradlew clean test -Dmode=cloud -Dselenide.headless=false -Dselenide.browser="${{ inputs.BROWSER }}"
         continue-on-error: true
+
+      - name: add Env params to Allure report
+        shell: bash
+        run: |
+          echo "BROWSER=${{ inputs.BROWSER }}" >> allure-results/environment.properties
+
+      - name: Publish JUnit Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
 
       - name: Get Allure history
         uses: actions/checkout@v4.1.1
@@ -87,3 +128,9 @@ jobs:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_branch: gh-pages
           publish_dir: allure-history
+
+      - name: Adding markdown
+        run: |
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "Allure report has been generated" >> $GITHUB_STEP_SUMMARY
+          echo "- URL: ${{ needs.prepare.outputs.ALLURE_LINK }}" >> $GITHUB_STEP_SUMMARY
