adjust on-push pipeline to specify the version

diff --git a/.github/workflows/on-push.yml b/.github/workflows/on-push.yml
--- a/.github/workflows/on-push.yml
+++ b/.github/workflows/on-push.yml
@@ -12,9 +12,8 @@ permissions:
   id-token: write
 
 jobs:
-  build:
+  prepare_env:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4.1.1
@@ -27,14 +26,32 @@ jobs:
 
       - uses: browser-actions/setup-chrome@v1
         with:
-          install-chromedriver: true
+          install-dependencies: true
       - run: chrome --version
+
+  run_tests:
+    runs-on: ubuntu-latest
+    needs: prepare_env
+    steps:
+      - name: Get Chrome Version
+        id: chrome_version
+        run: echo "::set-output name=version::$(chrome --version | cut -d ' ' -f 2 | cut -d '.' -f 1)"
 
       - name: Build and Test with Gradle
         if: always()
-        run: |
-          ./gradlew clean test -Dselenide.headless=true
+        run: | # need to specify the browser version otherwise ChromeDriver fails for the 'latest' version value 
+          ./gradlew clean test -Dversion=${{ steps.chrome_version.outputs.version }} -Dselenide.headless=true
         continue-on-error: true
+
+  post_test_results:
+    runs-on: ubuntu-latest
+    needs: run_tests
+    steps:
+      - name: Publish JUnit Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
 
       - name: Get Allure history
         uses: actions/checkout@v4.1.1
